routes/web.php
<?php

use App\Http\Controllers\ArtikelController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\CommentController;
// use App\Http\Controllers\KategoriController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('index', ['title' => 'UTS SisPro Transaction']);
});

// Route::get('/artikel', function () {
//     return view('artikel');
// });

Route::resource('artikels', ArtikelController::class);
Route::resource('categories', CategoryController::class);

app/Models/Artikel.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Artikel extends Model
{
    use HasFactory;

    protected $table = "artikels";

    protected $fillable = ['judul', 'kategori_id', 'isi'];

    public function category()
    {
        return $this->belongsTo(Category::class, 'kategori_id', 'id');
    }
}

app/Http/Controllers/ArtikelController.php
<?php

namespace App\Http\Controllers;

use App\Models\Artikel;
use App\Models\Category;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class ArtikelController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */

    public function index()
    {
        $artikels = Artikel::with('category')->get();
        $categories = Category::all();
        return view('artikel/index', [
            'artikels' => $artikels,
            'categories' => $categories
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $categories = Category::all();
        return view('artikel/create', ['categories' => $categories]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        DB::beginTransaction();
        try {

            // $categories = new Category;
            // $categories->nama = $request->nama;
            // $categories->save();

            // $artikels = new Artikel;
            // $artikels->kategori_id = $request->category;
            // $artikels->judul = $request->judul;
            // $artikels->isi = $request->isi;
            // $artikels->save();
            // dd($request->nama);
            $artikels = Artikel::create([
                'kategori_id' => $request->nama,
                'judul' => $request->judul,
                'isi' => $request->isi,
            ]);
            $artikels->save();

            DB::commit();
        } catch (\Throwable $th) {
            dd($th);
            DB::rollBack();
            return redirect('artikels')->with('error', 'Terjadi Kesalahan');
        };
        return redirect('artikels')->with('status', 'Artikel berhasil dibuat!');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Artikel  $artikel
     * @return \Illuminate\Http\Response
     */
    public function show(Artikel $artikel)
    {
        $artikel->makeHidden(['kategori_id']);
        return view('artikel/show', compact('artikel'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Artikel  $artikel
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $artikel = Artikel::find($id);
        $categories = Category::all();

        return view('artikel.edit', compact('artikel', 'categories'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Artikel  $artikel
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        DB::beginTransaction();
        try {

            // $artikels = Artikel::find($request->id);

            // dd($artikels);
            $artikels = Artikel::whereId($id)->first();
            $artikels->update([
                'judul' => $request->judul,
                'kategori_id' => $request->nama,
                'isi' => $request->isi,
            ]);

            // $categories = new Category;
            // $categories->id = $request->nama;
            // $categories->save();

            // $artikels = new Artikel;
            // $artikels->judul = $request->judul;
            // $artikels->kategori_id = $request->nama;
            // $artikels->isi = $request->isi;
            // $artikels->save();

            DB::commit();
        } catch (\Throwable $th) {
            // dd($th);
            DB::rollBack();
            return redirect('artikels')->with('error', 'Terjadi Kesalahan');
        };
        return redirect('artikels')->with('status', 'Artikel berhasil diedit!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Artikel  $artikel
     * @return \Illuminate\Http\Response
     */
    public function destroy(Artikel $artikel)
    {
        $artikel->delete();

        return redirect('artikels')->with('status', 'Artikel berhasil dihapus!');
    }
}

resources/views/artikel/create.blade.php
@extends('layouts.v_template')
@section("content")

        <div class="container col-lg-8 mt-4">
        <div class="card">
            <div class="card-header">
            <h2>Create Artikel</h2>
            <form method="POST" action="{{ url('artikels') }}">
            @csrf
                <div class="form-group">
                    <label>Judul</label>
                    <input type="text" class="form-control" name="judul" value="">
                </div>
                <div class="form-group">
                    <label>Kategori</label>
                    {{-- <input type="text" class="form-control" name="nama" value=""> --}}
                    <div>
                        <select name="nama" class="form-control">
                            @foreach ($categories as $item)
                                <option value="{{$item->id}}">{{$item->nama}}</option>
                            @endforeach
                        </select>
                    </div>
                </div>
                <div class="form-group">
                    <label>Isi Artikel</label>
                    <textarea class="form-control" rows="4" name="isi"></textarea>
                </div>
                <a href="{{ url('artikels') }}" class="btn btn-secondary">
                    <i class="fa fa-plus"></i>Back
                </a>
                <button type="submit" class="btn btn-primary">Create</button>
            </form>
        </div>
        </div>

@endsection

resources/views/artikel/edit.blade.php
@extends('layouts.v_template')
@section("content")

        <div class="container col-lg-8 mt-4">
            <h2>Edit Artikel</h2>
            <form method="POST" action="{{ (isset($artikel))?route('artikels.update', $artikel->id):route('artikels.store') }}">
            @csrf
            @method('PUT')
                <input type="hidden" name="id" id="id" value="">
                <div class="form-group">
                    <label>Judul</label>
                    <input type="text" class="form-control" name="judul" value="{{old('judul', $artikel->judul)}}">
                </div>
                <div class="form-group">
                    <label>Kategori</label>
                    {{-- <input type="text" class="form-control" name="nama" value="{{old('nama', $artikel->category->nama)}}"> --}}
                    <select name="nama" class="form-control">
                        @foreach ($categories as $item)
                            <option value="{{$item->id}}" >{{$item->nama}}</option>
                            {{-- @if(old('item',$artikel->kategori_id)==$category->id) selected="selected" @endif --}}
                        @endforeach
                    </select>
                </div>
                <div class="form-group">
                    <label>Isi Artikel</label>
                    <textarea class="form-control" rows="4" name="isi">{{old('isi', $artikel->isi)}}</textarea>
                </div>
                <a href="{{ url('artikels') }}" class="btn btn-secondary">
                    <i class="fa fa-plus"></i>Back
                </a>
                <button type="submit" class="btn btn-primary">Save</button>
            </form>
        </div>

@endsection

resources/views/artikel/index.blade.php
@extends('layouts.v_template')
@section("content")
        
        <div class="container col-lg-8 mt-3">
        <div class="card">
        @if (session('status'))
            <div class="alert alert-success">
                {{ session('status') }}
            </div>
        @endif
        @if (session('error'))
            <div class="alert alert-danger">
                {{ session('error') }}
            </div>
        @endif
            <div class="card-header">
                <div class="float-left">
                    <h2><strong>Data Artikel</strong></h2>
                </div>  
                <div class="float-right">
                <a href="{{ url('artikels/create') }}" class="btn btn-success">
                    <i class="fa fa-plus">Add</i>
                </a>
            </div>  
            </div>
            
            
            <div class="card-body table-responsive">
                <table class="table table-hover mt-2">
                    <thead>
                        <tr>
                            <th scope="col">No</th>
                            <th scope="col">Judul</th>
                            <th scope="col">Kategori</th>
                            <th scope="col">Isi</th>
                            <th></th>
                            <th scope="col">Opsi</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach ($artikels as $item)
                        <tr>
                            <td scope="row">{{$loop->iteration}}</td>
                            <td scope="row">{{$item->judul}}</td>
                            <td scope="row">{{$item->category->nama}}</td>
                            <td scope="row">{{$item->isi}}</td>
                            <td scope="row">
                                <a href="{{url('artikels/'.$item->id)}}">
                                    <button class="btn btn-link">Detail</button>
                                </a>
                            </td>
                            <td scope="row">
                                <a href="{{route('artikels.edit', $item->id)}}">
                                    <button class="btn btn-link">Edit</button>
                                </a>
                            </td>
                            <td scope="row">
                                <form action="{{url('artikels/'.$item->id)}}" method="POST" onsubmit="return confirm('Yakin hapus data?')">
                                    @method('delete')
                                    @csrf
                                    <button class="btn btn-link">Delete</button>
                                </form>
                            </td>
                        </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div>

        @endsection

resources/views/artikel/show.blade.php
@extends('layouts.v_template')
@section("content")

<div class="container col-lg-8 mt-3">
        
    <div class="card">
        @if (session('status'))
            <div class="alert alert-success">
                {{ session('status') }}
            </div>
        @endif
        @if (session('error'))
            <div class="alert alert-danger">
                {{ session('error') }}
            </div>
        @endif
            <div class="card-header">
                <div class="float-left">
                    <h2><strong>Detail Artikel</strong></h2>
                </div>
            </div>
            <div class="card-body table-responsive">
                <table class="table table-hover mt-2">
                    <tbody>
                        <tr>
                            <th>Judul artikel</th>
                            <td>{{$artikel->judul}}</td>
                        </tr>
                        <tr>
                            <th>Kategori artikel</th>
                            <td>{{$artikel->category->nama}}</td>
                        </tr>
                        <tr>
                            <th>Isi artikel</th>
                            <td>{{$artikel->isi}}</td>
                        </tr>
                        <tr>
                            <th>Created at</th>
                            <td>{{$artikel->created_at}}</td>
                        </tr>
                        <tr>
                            <th>Updated at</th>
                            <td>{{$artikel->updated_at}}</td>
                        </tr>
                    </tbody>
                </table>
                <div class="float-right">
                <a href="{{ url('artikels') }}" class="btn btn-primary">
                    <i class="fa fa-plus"></i>Back
                </a>
            </div>  
            </div>
        </div>
        </div>
        </div>

        @endsection