routes/web.php
<?php

use App\Http\Controllers\ArtikelController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\CommentController;
// use App\Http\Controllers\KategoriController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('index', ['title' => 'UTS SisPro Transaction']);
});

// Route::get('/artikel', function () {
//     return view('artikel');
// });

Route::resource('artikels', ArtikelController::class);
Route::resource('categories', CategoryController::class);

app/Models/Category.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    use HasFactory;

    // public function Artikel()
    // {
    //     return $this->hasMany(Artikel::class);
    // }
    protected $table = "categories";
    protected $fillable = ['nama'];
}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use App\Models\Category;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Http;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $categories = Category::all();
        return view('category/index', ['categories' => $categories]);
        $response = Http::get('http://localhost:3000/api/kategori/' . $categories->id,);
        $jsonDatas = $response->json();
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $categories = Category::all();
        return view('category/create', compact('categories'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        DB::beginTransaction();
        try {

            $categories = new Category;
            $categories->nama = $request->nama;
            $categories->save();

            //create category di api
            $response = Http::post('http://localhost:3030/api/kategori/', [
                'kategoriID' => $categories->id,
                'nama' => $request->nama,
            ]);

            DB::commit();
        } catch (\Throwable $th) {
            DB::rollBack();
            return redirect('categories')->with('error', 'Terjadi Kesalahan');
        };
        return redirect('categories')->with('status', 'Kategori berhasil dibuat!');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function show(Category $category)
    {
        // $category->makeHidden(['kategori_id']);
        return view('category/show', compact('category'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function edit(Category $category)
    {
        return view('category.edit', compact('category'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        DB::beginTransaction();
        try {

            $categories = Category::whereId($id)->first();
            $categories->update([
                'nama' => $request->nama,
            ]);


            // $categories = new Category;
            // $categories->nama = $request->nama;
            // $categories->save();

            // $artikels = new Artikel;
            // $artikels->kategori_id = $categories->id;
            // $artikels->judul = $request->judul;
            // $artikels->isi = $request->isi;
            // $artikels->save();

            DB::commit();
            //update category tabel di api
            $response = Http::patch('http://localhost:3030/api/kategori/' . $categories->id, [
                'kategoriID' => $categories->id,
                'nama' => $request->nama,
            ]);
        } catch (\Throwable $th) {
            dd($th);
            DB::rollBack();
            return redirect('categories')->with('error', 'Terjadi Kesalahan');
        };
        return redirect('categories')->with('status', 'Kategori berhasil diedit!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $category = Category::whereId($id)->first();
        $response = Http::delete('http://localhost:3030/api/kategori/' . $category->id);
        $category->delete();

        return redirect('categories')->with('status', 'Kategori berhasil dihapus!');
    }
}

resources/views/category/create.blade.php
@extends('layouts.v_template')
@section("content")

        <div class="container col-lg-8 mt-4">
        <div class="card">
            <div class="card-header">
            <h2>Create Kategori</h2>
            <form method="POST" action="{{ url('categories') }}">
            @csrf
                <div class="form-group">
                    <label>Nama</label>
                    <input type="text" class="form-control" name="nama" value="">
                </div>
                <button type="submit" class="btn btn-primary">Create</button>
            </form>
        </div>
        </div>

@endsection

resources/views/category/edit.blade.php
@extends('layouts.v_template')
@section("content")

        <div class="container col-lg-8 mt-4">
            <h2>Edit Kategori</h2>
            <form method="POST" action="{{ (isset($category))?route('categories.update', $category->id):route('categories.store')  }}">
            @csrf
            @method('PUT')
                <div class="form-group">
                    <label>Nama</label>
                    <input type="text" class="form-control" name="nama" value="{{old('nama', $category->nama)}}">
                </div>
                <a href="{{ url('categories') }}" class="btn btn-secondary">
                    <i class="fa fa-plus"></i>Back
                </a>
                <button type="submit" class="btn btn-primary">Save</button>
            </form>
        </div>

@endsection

resources/views/category/index.blade.php
@extends('layouts.v_template')
@section("content")
        
        <div class="container col-lg-8 mt-3">
        <div class="card">
        @if (session('status'))
            <div class="alert alert-success">
                {{ session('status') }}
            </div>
        @endif
        @if (session('error'))
            <div class="alert alert-danger">
                {{ session('error') }}
            </div>
        @endif
            <div class="card-header">
                <div class="float-left">
                    <h2><strong>Data Kategori</strong></h2>
                </div>  
                <div class="float-right">
                <a href="{{ url('categories/create') }}" class="btn btn-success">
                    <i class="fa fa-plus">Add</i>
                </a>
            </div>  
            </div>
            
            
            <div class="card-body table-responsive">
                <table class="table table-hover mt-2">
                    <thead>
                        <tr>
                            <th scope="col">No</th>
                            <th scope="col">Nama Kategori</th>
                            <th scope="col">Opsi</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach ($categories as $item)
                        <tr>
                            <td scope="row">{{$loop->iteration}}</td>
                            <td scope="row">{{$item->nama}}</td>
                            <td scope="row">
                                <a href="{{route('categories.edit', $item->id)}}">
                                    <button class="btn btn-link">Edit</button>
                                </a>
                            </td>
                            <td scope="row">
                                <form action="{{url('categories/'.$item->id)}}" method="POST" onsubmit="return confirm('Yakin hapus data?')">
                                    @method('delete')
                                    @csrf
                                    <button class="btn btn-link">Delete</button>
                                </form>
                            </td>
                        </tr>    
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div>

        @endsection

resources/views/category/show.blade.php
@extends('layouts.v_template')
@section("content")

<div class="container col-lg-8 mt-3">
        
    <div class="card">
        @if (session('status'))
            <div class="alert alert-success">
                {{ session('status') }}
            </div>
        @endif
        @if (session('error'))
            <div class="alert alert-danger">
                {{ session('error') }}
            </div>
        @endif
            <div class="card-header">
                <div class="float-left">
                    <h2><strong>Detail Kategori</strong></h2>
                </div>
            </div>
            <div class="card-body table-responsive">
                <table class="table table-hover mt-2">
                    <tbody>
                        <tr>
                            <th>Nama Kategori</th>
                            <td>{{$category->nama}}</td>
                        <tr>
                            <th>Created at</th>
                            <td>{{$category->created_at}}</td>
                        </tr>
                        <tr>
                            <th>Updated at</th>
                            <td>{{$category->updated_at}}</td>
                        </tr>
                    </tbody>
                </table>
                <div class="float-right">
                <a href="{{ url('categories') }}" class="btn btn-primary">
                    <i class="fa fa-plus"></i>Back
                </a>
            </div>  
            </div>
        </div>
        </div>
        </div>

        @endsection